name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      pending: ${{ steps.set-pending.outputs.pending }}
    steps:
      - uses: wyvox/action@v1
        with:
          node-version: 18.18.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cd docs-app
      - run: pnpm build
      - id: set-pending
        run: echo "pending=$(./cache-status.sh)" >> $GITHUB_OUTPUT
      - run:  echo ${{ github.event.number }} > ./pr-number.txt

  # Every PR will need linting. Turbo's cache can optimize per-package
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm lint
