name: Push dist

on:
  push:
    branches:
      - main
      - master

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: NullVoxPopuli/action-setup-pnpm@v2.3.1
      - run: git config --global url."https://github.com/".insteadOf "git@github.com:" && git config --global url."https://".insteadOf git://
      - working-directory: docs-app
        run: pnpm i git+https://github.com/patricklx/rollup-plugin-astroturf.git#dist
      - working-directory: docs-app
        run: pnpm i git+https://github.com/patricklx/kolay#dist-kolay
      - working-directory: docs-app
        run: pnpm i github:patricklx/kolay#dist-kolay-ui
      - run: pnpm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-app/dist
          publish_branch: ember-native-docs
      - uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ember-native
